apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountingservice
  namespace: otel-demo
  labels:
    app: accountingservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accountingservice
  template:
    metadata:
      labels:
        app: accountingservice
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault-secrets
      containers:
        - name: accountingservice
          image: myacr.azurecr.io/accountingservice:latest  # Update with your ACR
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: "accounting-db"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: accounting-db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accounting-db-secret
                  key: password
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: accountingservice
  namespace: otel-demo
spec:
  selector:
    app: accountingservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: otel-demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "<YOUR-KEYVAULT-NAME>"
    objects:  |
      array:
        - |
          objectName: "database-username"
          objectType: secret
        - |
          objectName: "database-password"
          objectType: secret
    tenantId: "<YOUR-AZURE-TENANT-ID>"
---
apiVersion: v1
kind: Secret
metadata:
  name: accounting-db-secret
  namespace: otel-demo
  labels:
    app: accountingservice
    type: database-credentials
type: Opaque
data:
  username: "YWNjb3VudGluZw=="  # Base64 encoded value of 'accounting'
  password: "/mnt/secrets-store/database-password"
